# You are given two strings s and t.
#
# String t is generated by random shuffling string s and then add one more letter at a random position.
#
# Return the letter that was added to t.

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        for i in t:
            if s.count(i) != t.count(i):
                return i

    def findTheDifference2(self, s: str, t: str) -> str:
        countT = 0
        countS = 0

        for i in s:
            countS += ord(i)
        for i in t:
            countT += ord(i)
        return chr(countT - countS)